* Encoding: UTF-8.
* Encoding: .
CORRELATIONS
  /VARIABLES=Temperature Density Rate Vibration Shift Impurities Defect
  /PRINT=TWOTAIL NOSIG FULL
  /MISSING=PAIRWISE.
GRAPH
  /SCATTERPLOT(BIVAR)=Temperature WITH Defect
  /MISSING=LISTWISE.
GRAPH
  /SCATTERPLOT(BIVAR)=Density WITH Defect
  /MISSING=LISTWISE.
GRAPH
  /SCATTERPLOT(BIVAR)=Rate WITH Defect
  /MISSING=LISTWISE.
GRAPH
  /SCATTERPLOT(BIVAR)=Vibration WITH Defect
  /MISSING=LISTWISE.
GRAPH
  /SCATTERPLOT(BIVAR)=Impurities WITH Defect
  /MISSING=LISTWISE.
GRAPH
  /SCATTERPLOT(BIVAR)=Rate WITH Temperature
  /MISSING=LISTWISE.
GRAPH
  /SCATTERPLOT(BIVAR)=Density WITH Temperature
  /MISSING=LISTWISE.
GRAPH
  /SCATTERPLOT(BIVAR)=Density WITH Rate
  /MISSING=LISTWISE.
GRAPH
  /SCATTERPLOT(BIVAR)=Rate WITH Impurities
  /MISSING=LISTWISE.
GRAPH
  /SCATTERPLOT(BIVAR)=Impurities WITH Defect
  /MISSING=LISTWISE.
PARTIAL CORR
  /VARIABLES=Vibration Density Shift Impurities Defect BY Rate Temperature
  /SIGNIFICANCE=TWOTAIL
  /MISSING=LISTWISE.
PARTIAL CORR
  /VARIABLES=Vibration Temperature Shift Impurities Defect BY Rate Density
  /SIGNIFICANCE=TWOTAIL
  /MISSING=LISTWISE.
PARTIAL CORR
  /VARIABLES=Vibration Rate Shift Impurities Defect BY Density Temperature
  /SIGNIFICANCE=TWOTAIL
  /MISSING=LISTWISE.
PARTIAL CORR
  /VARIABLES=Vibration Density Rate Shift Impurities Defect BY Temperature
  /SIGNIFICANCE=TWOTAIL
  /MISSING=LISTWISE.
PARTIAL CORR
  /VARIABLES=Vibration Temperature Rate Shift Impurities Defect BY Density
  /SIGNIFICANCE=TWOTAIL
  /MISSING=LISTWISE.
PARTIAL CORR
  /VARIABLES=Vibration Temperature Density Shift Impurities Defect BY Rate
  /SIGNIFICANCE=TWOTAIL
  /MISSING=LISTWISE.
REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Defect
  /METHOD=ENTER Density Shift Vibration Temperature Rate Impurities
  /SCATTERPLOT=(*ZRESID ,*ZPRED).
REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Defect
  /METHOD=ENTER Temperature
  /SCATTERPLOT=(*ZRESID ,*ZPRED).
REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Defect
  /METHOD=ENTER Density
  /SCATTERPLOT=(*ZRESID ,*ZPRED).
REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Defect
  /METHOD=ENTER Vibration
  /SCATTERPLOT=(*ZRESID ,*ZPRED).
REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Defect
  /METHOD=ENTER Impurities
  /SCATTERPLOT=(*ZRESID ,*ZPRED).
REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Defect
  /METHOD=ENTER Shift
  /SCATTERPLOT=(*ZRESID ,*ZPRED).
REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Defect
  /METHOD=ENTER Rate
  /SCATTERPLOT=(*ZRESID ,*ZPRED).



REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Defect
  /METHOD=ENTER Vibration Temperature
  /SCATTERPLOT=(*ZRESID ,*ZPRED).
REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Defect
  /METHOD=ENTER Vibration Density
  /SCATTERPLOT=(*ZRESID ,*ZPRED).
REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Defect
  /METHOD=ENTER Vibration Rate
  /SCATTERPLOT=(*ZRESID ,*ZPRED).
REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Defect
  /METHOD=ENTER Vibration Impurities
  /SCATTERPLOT=(*ZRESID ,*ZPRED).
REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Defect
  /METHOD=ENTER Vibration Shift
  /SCATTERPLOT=(*ZRESID ,*ZPRED).

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Defect
  /METHOD=ENTER Vibration Temperature Density
  /SCATTERPLOT=(*ZRESID ,*ZPRED).
REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Defect
  /METHOD=ENTER Vibration Temperature Rate
  /SCATTERPLOT=(*ZRESID ,*ZPRED).
REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Defect
  /METHOD=ENTER Vibration Temperature Impurities
  /SCATTERPLOT=(*ZRESID ,*ZPRED).
REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Defect
  /METHOD=ENTER Vibration Temperature Shift
  /SCATTERPLOT=(*ZRESID ,*ZPRED).

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Defect
  /METHOD=ENTER Vibration Temperature Impurities Density
  /SCATTERPLOT=(*ZRESID ,*ZPRED).
REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Defect
  /METHOD=ENTER Vibration Temperature Impurities Rate
  /SCATTERPLOT=(*ZRESID ,*ZPRED).
REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Defect
  /METHOD=ENTER Vibration Temperature Impurities Shift
  /SCATTERPLOT=(*ZRESID ,*ZPRED).

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Defect
  /METHOD=ENTER Vibration Temperature Impurities Shift Rate
  /SCATTERPLOT=(*ZRESID ,*ZPRED).
REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Defect
  /METHOD=ENTER Vibration Temperature Impurities Shift Density
  /SCATTERPLOT=(*ZRESID ,*ZPRED).



REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Defect
  /METHOD=FORWARD Vibration Impurities Shift Rate Temperature Density
  /SCATTERPLOT=(*ZRESID ,*ZPRED).

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Defect
  /METHOD=BACKWARD Vibration Impurities Shift Rate Temperature Density
  /SCATTERPLOT=(*ZRESID ,*ZPRED).



*Automatic Linear Modeling. 
LINEAR 
  /FIELDS TARGET=Defect INPUTS=Temperature Density Rate Vibration Shift Impurities 
  /BUILD_OPTIONS OBJECTIVE=STANDARD USE_AUTO_DATA_PREPARATION=TRUE CONFIDENCE_LEVEL=95 
    MODEL_SELECTION=BESTSUBSETS CRITERIA_BEST_SUBSETS=ADJUSTEDRSQUARED REPLICATE_RESULTS=TRUE 
    SEED=54752075
  /ENSEMBLES COMBINING_RULE_CONTINUOUS=MEAN COMPONENT_MODELS_N=10.


REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Defect
  /METHOD=ENTER Vibration Temperature Shift Impurities
  /SCATTERPLOT=(*ZRESID ,*ZPRED).
REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Defect
  /METHOD=ENTER Vibration Temperature Shift Impurities Density
  /SCATTERPLOT=(*ZRESID ,*ZPRED).
REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Defect
  /METHOD=ENTER Vibration Temperature Impurities Density
  /SCATTERPLOT=(*ZRESID ,*ZPRED).



DATASET ACTIVATE DataSet1.
REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Defect
  /METHOD=ENTER Shift.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Defect
  /METHOD=ENTER Impurities.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Defect
  /METHOD=ENTER Vibration Temperature Shift Impurities
  /SCATTERPLOT=(*ZRESID ,*ZPRED)
  /SAVE ZRESID
  /SAVE RESID.


GRAPH
  /HISTOGRAM(NORMAL)=ZRE_1.



DATASET ACTIVATE DataSet1.
EXAMINE VARIABLES=ZRE_1
  /PLOT BOXPLOT STEMLEAF NPPLOT
  /COMPARE GROUPS
  /STATISTICS DESCRIPTIVES
  /CINTERVAL 95
  /MISSING LISTWISE
  /NOTOTAL.

COMPUTE RES_SQ=RES_1 ** 2.
EXECUTE.



REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT RES_SQ
  /METHOD=ENTER Temperature Vibration Shift Impurities.

UNIANOVA Defect WITH Temperature Vibration Shift Impurities
  /METHOD=SSTYPE(3)
  /INTERCEPT=INCLUDE
  /PRINT WHITE BP PARAMETER
  /CRITERIA=ALPHA(.05)
  /DESIGN=Temperature Vibration Shift Impurities.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA
  /CRITERIA=PIN(.05) POUT(.10) TOLERANCE(.0001)
  /NOORIGIN 
  /DEPENDENT Defect
  /METHOD=ENTER Temperature Vibration Shift Impurities Rate.


